### ISSUE TITLE
CONDITIONAL 3: Add the repository to Apt sources

### ISSUE THREAD

**Issue by MonetCarriere** [Topher2014/DockerScript#13]
Put the following in a bash script:

**echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update**

**Comment by jlotto8** [comment]
merged
